config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :destroy, :edit, :show]
  resource :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  email           :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#

class User < ApplicationRecord
    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 8, allow_nil: true }
    attr_reader :password
    after_initialize :ensure_session_token

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def reset_token!
        self.session_token = User::generate_session_token
    end

    def ensure_session_token
        self.session_token ||= self.reset_token!
    end

    def password=(pw)
        self.password_digest = BCrypt::Password.create(pw)
    end

    def is_password?(pw)
       BCrypt::Password.new(self.password_digest).is_password?(pw)
    end

    def self.find_by_credentials(email, password)
        found_user = User.find_by(email: email)
        return found_user if found_user.is_password?(password)           
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        User.find_by(session_token: session[:session_token])
    end
    
    def login!(user)
        session[:session_token] = user.reset_token!
    end

    def logout!(user)
        session[:session_token] = nil
        user.reset_token!
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # render login page
  def new
  end

  # log user in 
  def create
    @user = User::find_by_credentials(params[:user][:email], params[:user][:password])
    redirect_to users_url(params[:sessions][:user_id])
  end

  def destroy
    logout!(current_user)
    redirect_to new_sessions_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end

    def create
        @user = User.new(user_params)
        @user.password = user_params[:password]
        @user.save!
        login!(@user)
        render plain: "user saved probably"
    end

    def show
        
    end
    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Welcome to the Siknessss</h1>
<h3>musikss</h3>
<h2>more mmmm</h2>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form method="post" action="<%= users_url %>">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    Email:<label>
        <input type="email" name="user[email]" value="email">
    </label>
    <br>
    Password:<label>
        <input type="password" name="user[password]" value="password">
    </label>

    <input type="submit" value="Sign Up!">
</form>

app/views/users/show.html.erb
<h1>Hellooooooooooo</h1>

<form method="post" action="<%= sessions_url %>">
    <input type="hidden" method="delete" name="authenticity_token" value="<%= form_authenticity_token %>">

    <input type="submit" value="Log Out!">
</form>